### ISSUE TITLE
[VAX-893] Android support current broken.

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric#473] opened 2023-09-21 14:18 UTC
Was just testing the expo and RN examples in Android. Both throw this error:

`Queries can be performed using SQLiteDatabase query or rawQuery methods only.`

There's a few results online, e.g.: [https://www.b4x.com/android/forum/threads/sqlite-and-pragma.16410/](https://www.b4x.com/android/forum/threads/sqlite-and-pragma.16410/)

Needs more investigation but seems like we need to change the functions we're using to execute SQL statements. This currently blocks anything working on Android.

<sub>From [SyncLinear.com](https://synclinear.com) | [VAX-893](https://linear.app/electric-sql/issue/VAX-893/android-support-current-broken)</sub>

**Comment by balegas** [comment] 2023-09-21 14:19
We've identified the cause. There is a fix already available for Expo, but we need to investigate RN driver

**Comment by kevin-dp** [comment] 2023-09-21 14:23
Additional details can be found here:
[](https://github.com/expo/expo/issues/24283)

**Comment by balegas** [comment] 2023-10-11 22:55
We now have Expo working, but still missing React Native

**Comment by kevin-dp** [comment] 2023-10-23 11:00
> We now have Expo working, but still missing React Native

Actually, expo-sqlite pushed a workaround but we are not yet using it.

**Comment by kevin-dp** [comment] 2023-11-07 10:59
This was fixed in https://github.com/electric-sql/electric/pull/592 and is now released in electric-sql v0.7.0.

**Closed** 2023-11-07 11:31 UTC
Labels: bug
