### ISSUE TITLE
Electric doesn't clean shapes after connecting to a new postgres with a different schema

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1689] opened 2024-09-13 15:50 UTC
steps to reproduce:
1. Follow the quickstart and add the table `foo` with a few rows of data
2. Fetch the foo table shape
3. Restart Postgres as an empty db
4. Electric reconnects
5. Try fetching the foo shape and see that the old data is returned instead of the table not found error

[DIscord link](https://discord.com/channels/933657521581858818/1284172917059616970/1284177755935739925)

**Comment by KyleAMathews** [comment] 2024-09-13 15:55
lirbank (discord user name) also tried inserting new rows into the new database (with identical table) and those weren't added to the shape. So perhaps we're also missing adding the right publication when we connect to the new db? cc @kevin-dp

**Comment by lirbank** [comment] 2024-09-13 16:06
@lirbank on GH too 😃

**Comment by thruflo** [comment] 2024-09-13 17:24
I've slightly addressed this here https://electric-sql.com/docs/guides/troubleshooting#clear-data-mdash-how-do-i-clear-the-server-state -- I wonder (a) if we want to add some functionality to wipe shapes when PG changes or (b) whether we want to be clearer about the behaviour and if so where and how to document.

One thing we've done before for telemetry is write a unique identifier into the PG instance. Perhaps one approach here could be when Electric starts it can get-or-create a uuid and then use it internally as part of the shape lookup.

**Comment by lirbank** [comment] 2024-09-14 17:11
I just did this:

1. Fired up the quickstart docker compose file
2. Created todo table, added 200,000 rows
3. Run the curl command, shows the 200,000 rows ✅
4. Dropped the todo table
5. Run the curl command, shows the 200,000 rows ❌
6. Create the todo table again, added 200,000 rows again but with different "task" names so it is clearly different from the original data set
5. Run the curl command, still shows the original 200,000 rows ❌

**Comment by KyleAMathews** [comment] 2024-09-14 17:21
ok so very broken 😬

**Comment by lirbank** [comment] 2024-09-14 20:06
Here is another:

1. Remove all docker containers and start fresh
2. Create the todo table
3. Insert some rows
4. Run `DELETE FROM todo;`
5. Now `curl -i 'http://localhost:3000/v1/shape/todo?offset=-1` still return the stale data
6. `SELECT COUNT(*) FROM todo;` return 0

Docker image is now canary:

`electricsql/electric:canary`
`sha256:5d0db221daf0f74d6dd2bbba034612d626e15905f3a784273b8e27c75c5e81cd`

**Comment by lirbank** [comment] 2024-09-14 20:28
FYI I have modified the docker-compose.yaml, not using tmpfs for postgres data coz it run out of storage.

```
version: "3.3"
name: "electric_quickstart"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    tmpfs:
      # - /var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric:canary
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric
    ports:
      - "3000:3000"
    depends_on:
      - postgres
```

**Comment by kevin-dp** [comment] 2024-09-16 06:57
> I just did this:
> 
>     1. Fired up the quickstart docker compose file
> 
>     2. Created todo table, added 200,000 rows
> 
>     3. Run the curl command, shows the 200,000 rows ✅
> 
>     4. Dropped the todo table
> 
>     5. Run the curl command, shows the 200,000 rows ❌
> 
>     6. Create the todo table again, added 200,000 rows again but with different "task" names so it is clearly different from the original data set
> 
>     7. Run the curl command, still shows the original 200,000 rows ❌

Postgres doesn't publish DDL statements on the logical replication stream, so Electric can't know that you dropped the table. After dropping the table, you should delete the shape which will force Electric to clean the shape.

**Comment by kevin-dp** [comment] 2024-09-16 07:05
@KyleAMathews Electric currently assumes that the Postgres database remains the same. If the PG database remains the same but you drop all tables, then you should also (manually) drop all shapes. If you restart Electric but let it connect to a different database, then it most probably won't work unless the database is in the exact same state as the original one. It seems that every PG instance has a unique ID, so we could detect this. We could wipe all Electric state when detecting that the DB changed, or throw an error telling the user to start a fresh Electric for this new DB?

**Comment by KyleAMathews** [comment] 2024-09-16 11:40
> If the PG database remains the same but you drop all tables, then you should also (manually) drop all shapes

Why's this? We can't detect a table is dropped?

**Comment by kevin-dp** [comment] 2024-09-16 11:51
Re-opening since detecting change of DB is not completely solving the issue. We also need to properly clean up persisted shapes.

**Comment by kevin-dp** [comment] 2024-09-16 11:52
> > If the PG database remains the same but you drop all tables, then you should also (manually) drop all shapes
> 
> Why's this? We can't detect a table is dropped?

Because Postgres logical replication does not stream DDL statements like `DROP TABLE`.

**Comment by thruflo** [comment] 2024-09-16 11:53
@kevin-dp there’s also the aspect of dropped and recreated tables from the same PG.

**Comment by kevin-dp** [comment] 2024-09-16 11:55
> @kevin-dp there’s also the aspect of dropped and recreated tables from the same PG.

I have described one such corner case that can occur here: https://github.com/electric-sql/electric/pull/1562.
But for it to work correctly, after dropping the table you should delete the shape (even if you're going to recreate the table afterwards).

**Comment by KyleAMathews** [comment] 2024-09-16 12:01
Maybe we just need a "purge_all" API for cases like this.

**Comment by thruflo** [comment] 2024-09-16 12:21
Re: drop table, have we explored all creative avenues?

a) is there a trigger than can run in response to a drop?
b) how does PG handle table identify internally? Is there any way of detecting that a dropped and created table is different, thus invalidating the shape at that point?
c) could be implement table identity ourselves, eg with a metadata column?
d) can we detect publication changes / any introspection on a publication?

Just listing some ideas that spring to mind. I’m sure we’ve looked into this previously.

**Comment by kevin-dp** [comment] 2024-09-16 12:27
@thruflo I did not explore other options. Perhaps @magnetised did that some time ago for old Electric. A quick search revealed that Postgres supports event triggers which unlike regular triggers can detect DDL statements. It seems that those event triggers can detect tables being dropped. Looking into it.

**Comment by alco** [comment] 2024-09-16 12:31
> a) is there a trigger than can run in response to a drop?

This falls into the realm of [Event Triggers](https://www.postgresql.org/docs/current/event-trigger-matrix.html) which require the superuser privilege.

>  b) how does PG handle table identify internally? Is there any way of detecting that a dropped and created table is different, thus invalidating the shape at that point?

Each table gets its own unique object identifier (OID) and all tables are accessible via the builtin [`pg_class`](https://www.postgresql.org/docs/current/catalog-pg-class.html) relation.

> d) can we detect publication changes / any introspection on a publication?

Event triggers only.

**Comment by alco** [comment] 2024-09-16 12:33
@kevin-dp We used event triggers a while ago in the old Electric before deciding that requiring the superuser privilege was untenable. That's when the migrations proxy idea was born, so that Electric could intercept DDL commands without requiring additional privileges in Postgres.

**Comment by KyleAMathews** [comment] 2024-09-16 12:39
Can you query for ddl commands that have been run lately? Especially in dev we could probably just query for schema/ddl info every second or something to see what's been happening. Even in prod we could probably do this periodically to clean up shapes. And/or expose this as a command so people can run it after they do a migration.

**Comment by kevin-dp** [comment] 2024-09-16 12:44
> Can you query for ddl commands that have been run lately? Especially in dev we could probably just query for schema/ddl info every second or something to see what's been happening. Even in prod we could probably do this periodically to clean up shapes. And/or expose this as a command so people can run it after they do a migration.

I don't think a DDL log like this exists (other than scraping the actual logs).
We could, however, extend each shape to also keep track of the root table's OID and periodically check that it didn't change. But if someone inserts/updates/deletes after the table has been dropped and recreated, and before our periodic check picked it up, then all bets are off...

**Comment by KyleAMathews** [comment] 2024-09-16 12:53
> then all bets are off...

Yeah for sure — this is mostly useful for dev when people either a) don't know how our system works yet or b) are doing lots of ad hoc migrations and us just cleaning things up is a lot easier.

In prod, we'd want people to call the command to purge shapes related to DDL changes.

**Comment by thruflo** [comment] 2024-09-16 12:56
Just an observation with the purge command: if you provide a function inside PG like `CALL electric_purge_all()` then you can run it within the DDL transaction and have Electric act on it at the right moment.

If you do it as an API / CLI call, you don't get the same consistency guarantee.

The implementation would write a record that Electric looks for in the replication stream.

**Comment by KyleAMathews** [comment] 2024-09-16 13:20
ooo yes, doing it inside PG would be much better @thruflo!

**Comment by lirbank** [comment] 2024-09-16 13:21
Please note that this also happens when deleting all rows of a table (not dropping the table):

https://github.com/electric-sql/electric/issues/1689#issuecomment-2351132507

**Comment by kevin-dp** [comment] 2024-09-16 13:35
> Please note that this also happens when deleting all rows of a table (not dropping the table):
> 
> [#1689 (comment)](https://github.com/electric-sql/electric/issues/1689#issuecomment-2351132507)

I believe this should not happen and is indeed a bug. Afaik we do support truncates so there may be a bug with the way how we handle truncates.

**Comment by kevin-dp** [comment] 2024-09-30 11:08
Closing this issue as we now detect when Electric is restarted with a different PG DB (https://github.com/electric-sql/electric/pull/1703) and we also clean up persisted shapes (https://github.com/electric-sql/electric/pull/1705). I'm opening a separate issue to address the bug discussed in https://github.com/electric-sql/electric/issues/1689#issuecomment-2351132507.

**Closed by kevin-dp** 2024-09-30 11:08 UTC
Labels: bug

**Comment by kevin-dp** [comment] 2024-09-30 11:34
> Here is another:
> 
>     1. Remove all docker containers and start fresh
> 
>     2. Create the todo table
> 
>     3. Insert 200,000 rows
> 
>     4. Run `DELETE FROM todo;`
> 
>     5. Now `curl -i 'http://localhost:3000/v1/shape/todo?offset=-1` still return the stale data ❌
> 
>     6. `SELECT COUNT(*) FROM todo;` return 0
> 
> 
> Docker image is now canary:
> 
> `electricsql/electric:canary` `sha256:5d0db221daf0f74d6dd2bbba034612d626e15905f3a784273b8e27c75c5e81cd`
> 
> I add all the rows with:
> 
> ```sql
> INSERT INTO todo (task, done)    
> SELECT  'AAA Task ' || gs, (random() < 0.5)   
> FROM generate_series(1, 200000) AS gs;
> ```

@lirbank is this still an issue? I believe this may be solved by https://github.com/electric-sql/electric/pull/1705. I have not been able to reproduce this issue on latest main.
