### ISSUE TITLE
[Example apps][Expo] Broken Prisma client generation

### ISSUE THREAD

**Issue by atanaskanchev** [electric-sql/electric#966] opened 2024-02-19 10:43 UTC
### Steps to repro

1. Clone the repo
2. [Update all the dependencies](https://github.com/electric-sql/electric/pull/965/commits/e826612a15e0ecf015a738277d40caa33882cdcb) in the `/examples/expo` app to the latest and run expo doctor
3. [Update the pg and electric images](https://github.com/electric-sql/electric/pull/965/commits/6a7da6000f6e8be2f8f3c92fac9b95fda394ccec) to the latest
4. Run

* `yarn backend:up`
* `yarn db:migrate`
* `yarn client:generate`

### Reproducible example

[here](https://github.com/electric-sql/electric/pull/965)

### Expected

Prisma client to be generated in `src/generated/client`

### Actual

* The client generated in `[src/generated/client/prismaClient.d.ts](https://github.com/electric-sql/electric/pull/965/commits/821493ab8cf61387718ce6bb69859dfebbe40354#diff-35095d33d6c46aeb1a1f607fde67e110ee08628ac2bc9eedc5005a02690d2fe6)`[ ](https://github.com/electric-sql/electric/pull/965/commits/821493ab8cf61387718ce6bb69859dfebbe40354#diff-35095d33d6c46aeb1a1f607fde67e110ee08628ac2bc9eedc5005a02690d2fe6) has a broken import as `import * as runtime from './runtime/library.js';`
* ts errors in the generated `ItemsWhereUniqueInputSchema`

```ts
Type 'ZodObject<{ value: ZodOptional; }, "strict", ZodTypeAny, { value?: string | undefined; }, { value?: string | undefined; }>' is not assignable to type 'ZodType'.
  Types of property '_type' are incompatible.
    Type '{ value?: string | undefined; }' is not assignable to type 'ItemsWhereUniqueInput'.
      Type '{ value?: string | undefined; }' is not assignable to type '{ value: string; } & { value?: string | undefined; AND?: ItemsWhereInput | ItemsWhereInput[] | undefined; OR?: ItemsWhereInput[] | undefined; NOT?: ItemsWhereInput | ... 1 more ... | undefined; }'.
        Type '{ value?: string | undefined; }' is not assignable to type '{ value: string; }'.
          Types of property 'value' are incompatible.
            Type 'string | undefined' is not assignable to type 'string'.
              Type 'undefined' is not assignable to type 'string'.ts(2322)
```

**Comment by msfstef** [comment] 2024-02-28 10:52
Closing as duplicate of https://github.com/electric-sql/electric/issues/1001 - see PR https://github.com/electric-sql/electric/pull/1016 for progress on resolving this

**Closed by msfstef** 2024-02-28 10:52 UTC
